import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_four.dart';import 'package:fintech_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class DSingleTransactionScreen extends StatelessWidget {const DSingleTransactionScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildArrowLeft(context), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 3.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgFrame162757, height: 34.adaptSize, width: 34.adaptSize), SizedBox(height: 10.v), Text("£50", style: theme.textTheme.titleLarge), SizedBox(height: 2.v), Opacity(opacity: 0.6, child: Text("Transfer from Leah", style: CustomTextStyles.labelLargeSFProTextBlack900_2)), SizedBox(height: 26.v), _buildVector(context), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.fillGray100041, child: Column(children: [SizedBox(height: 7.v), CustomAppBar(height: 23.v, leadingWidth: 26.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftErrorcontainer, margin: EdgeInsets.only(left: 10.h, top: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleFour(text: "Help"), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgAmount22x22, margin: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 1.v))])])); } 
/// Section Widget
Widget _buildVector(BuildContext context) { return SizedBox(height: 273.v, width: 343.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgVectorTeal600, height: 15.v, width: 9.h, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 14.h, bottom: 92.v)), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Text("Select an issue", style: CustomTextStyles.labelLargeManropeGray90008))), SizedBox(height: 5.v), Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 17.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [_buildFrame(context, statusText: "Making changes to this transfer"), SizedBox(height: 43.v), _buildFrame(context, statusText: "Status of this transfer"), SizedBox(height: 44.v), _buildFrame(context, statusText: "Cancellations and refunds"), SizedBox(height: 50.v), _buildFrame(context, statusText: "Understanding fees & rates")]))]))])); } 
/// Common widget
Widget _buildFrame(BuildContext context, {required String statusText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.9, child: Text(statusText, style: CustomTextStyles.titleSmallGray90008.copyWith(color: appTheme.gray90008.withOpacity(0.67)))), CustomImageView(imagePath: ImageConstant.imgVectorTeal600, height: 15.v, width: 9.h, margin: EdgeInsets.only(bottom: 3.v))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
