import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:fintech_app/widgets/custom_icon_button.dart';import 'package:fintech_app/widgets/custom_switch.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class CUploadAnImage3ThreeScreen extends StatelessWidget {CUploadAnImage3ThreeScreen({Key? key}) : super(key: key);

bool isSelectedSwitch = false;

bool isSelectedSwitch1 = false;

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 14.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, alignment: Alignment.centerLeft, onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 23.v), _buildProfileNameAvatar(context), SizedBox(height: 11.v), _buildCreateANewSafebox(context), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 10.h), child: Text("Profile", style: CustomTextStyles.titleSmallInterBluegray30003))), SizedBox(height: 10.v), _buildCardContainerDocument(context), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 10.h), child: Text("Security", style: CustomTextStyles.titleSmallInterBluegray30003))), SizedBox(height: 9.v), _buildLine(context), SizedBox(height: 34.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 10.h), child: Text("General", style: CustomTextStyles.titleSmallInterBluegray30003))), SizedBox(height: 8.v), _buildNinetyFive(context), SizedBox(height: 3.v), Divider(indent: 10.h, endIndent: 8.h), SizedBox(height: 13.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 10.h), child: Text("Legal", style: CustomTextStyles.titleSmallInterBluegray30003))), SizedBox(height: 8.v), _buildNinetyFour(context), SizedBox(height: 24.v), _buildNinetyThree(context), SizedBox(height: 24.v), Text("Follow Us", style: CustomTextStyles.bodyMediumEudoxusSansGray50001), SizedBox(height: 16.v), Padding(padding: EdgeInsets.symmetric(horizontal: 46.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 49.adaptSize, width: 49.adaptSize, padding: EdgeInsets.all(13.h), child: CustomImageView(imagePath: ImageConstant.imgAkarIconsTwitterFillPrimary)), Padding(padding: EdgeInsets.only(left: 18.h), child: CustomIconButton(height: 49.adaptSize, width: 49.adaptSize, padding: EdgeInsets.all(13.h), child: CustomImageView(imagePath: ImageConstant.imgAkarIconsFacebookFillPrimary))), Padding(padding: EdgeInsets.only(left: 18.h), child: CustomIconButton(height: 49.adaptSize, width: 49.adaptSize, padding: EdgeInsets.all(13.h), child: CustomImageView(imagePath: ImageConstant.imgBxBxlTiktokPrimary))), Padding(padding: EdgeInsets.only(left: 18.h), child: CustomIconButton(height: 49.adaptSize, width: 49.adaptSize, padding: EdgeInsets.all(13.h), child: CustomImageView(imagePath: ImageConstant.imgAkarIconsInstagramFillPrimary)))]))]))))])))); } 
/// Section Widget
Widget _buildProfileNameAvatar(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Adrian UIUX", style: theme.textTheme.headlineMedium), SizedBox(height: 2.v), Text("Personal account", style: CustomTextStyles.titleMediumBluegray400)])), SizedBox(height: 60.v, width: 57.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(height: 56.adaptSize, width: 56.adaptSize, decoration: BoxDecoration(color: appTheme.lightBlueA400, borderRadius: BorderRadius.circular(28.h)))), CustomImageView(imagePath: ImageConstant.imgIntersect, height: 51.v, width: 57.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgFrame162701Teal600, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 4.h))]))])); } 
/// Section Widget
Widget _buildCreateANewSafebox(BuildContext context) { return SizedBox(height: 248.v, width: 343.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgStackGoldCoin247x343, height: 247.v, width: 343.h, radius: BorderRadius.circular(10.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgCloseButton, height: 44.adaptSize, width: 44.adaptSize, alignment: Alignment.centerRight), SizedBox(height: 113.v), Padding(padding: EdgeInsets.only(left: 14.h), child: Text("Create new Safebox", style: CustomTextStyles.headlineMediumOnErrorContainer)), Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 8.v), decoration: AppDecoration.fillGrayEf.copyWith(borderRadius: BorderRadiusStyle.customBorderBL8), child: Row(children: [Container(width: 187.h, margin: EdgeInsets.only(top: 1.v), child: Text("Set your financial goals and start\nsaving - we’ll do the rest!", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.labelLargeOnErrorContainerSemiBold12.copyWith(height: 1.33))), CustomElevatedButton(height: 34.v, width: 90.h, text: "Open now", margin: EdgeInsets.only(left: 37.h), buttonStyle: CustomButtonStyles.fillTeal, buttonTextStyle: CustomTextStyles.labelMediumManropeErrorContainer)]))]))])); } 
/// Section Widget
Widget _buildCardContainerDocument(BuildContext context) { return Container(width: 343.h, margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 16.v), decoration: AppDecoration.outlineGray4000c.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconInterBlueGray9000324x24, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Text("Card confirmation", style: theme.textTheme.titleMedium))]), SizedBox(height: 32.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconFinance, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Text("Account details", style: theme.textTheme.titleMedium))]), SizedBox(height: 32.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconFinance24x24, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 3.v), child: Text("Transaction history", style: theme.textTheme.titleMedium))]), SizedBox(height: 32.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconInter24x24, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Text("Documents", style: theme.textTheme.titleMedium))])])); } 
/// Section Widget
Widget _buildLine(BuildContext context) { return SizedBox(height: 321.v, width: 343.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 8.h, right: 8.h, bottom: 39.v), child: Column(mainAxisSize: MainAxisSize.min, children: [Divider(), SizedBox(height: 15.v), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgIconlyLightOutlineScan, height: 18.v, width: 22.h, margin: EdgeInsets.only(top: 3.v, bottom: 5.v)), Padding(padding: EdgeInsets.only(left: 16.h, bottom: 3.v), child: Text("Face Id", style: theme.textTheme.titleMedium)), Spacer(), CustomSwitch(margin: EdgeInsets.only(top: 3.v), value: isSelectedSwitch, onChange: (value) {isSelectedSwitch = value;})]), SizedBox(height: 21.v), Divider()]))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 48.h), child: Text("Hide balances", style: theme.textTheme.titleMedium))), Align(alignment: Alignment.bottomLeft, child: Container(height: 20.v, width: 16.h, margin: EdgeInsets.only(left: 12.h, bottom: 2.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyLightOutlineUnlock, height: 20.v, width: 16.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgIconlyLightOutlineUnlock, height: 20.v, width: 16.h, alignment: Alignment.center)]))), CustomSwitch(margin: EdgeInsets.only(right: 8.h), alignment: Alignment.bottomRight, value: isSelectedSwitch1, onChange: (value) {isSelectedSwitch1 = value;}), Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 16.v), decoration: AppDecoration.outlineGray4003f01.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgHugeIconInter1, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 260.v)), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 260.v), child: Text("Devices", style: theme.textTheme.titleMedium))])))])); } 
/// Section Widget
Widget _buildNinetyFive(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 20.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 3.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgVectorBlueGray9000221x18, height: 21.v, width: 18.h, margin: EdgeInsets.symmetric(vertical: 1.v)), Padding(padding: EdgeInsets.only(left: 18.h), child: Text("Notification", style: theme.textTheme.titleMedium))])), SizedBox(height: 24.v), Divider(), SizedBox(height: 15.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgLayer2, height: 19.adaptSize, width: 19.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 18.h), child: Text("Languages", style: theme.textTheme.titleMedium))]), SizedBox(height: 24.v), Divider(), SizedBox(height: 15.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgIconlyLightOu, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 18.h), child: Text("Help and Support", style: theme.textTheme.titleMedium))])])); } 
/// Section Widget
Widget _buildNinetyFour(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 20.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 3.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgVectorBlueGray9000221x18, height: 21.v, width: 18.h, margin: EdgeInsets.symmetric(vertical: 1.v)), Padding(padding: EdgeInsets.only(left: 18.h), child: Text("Privacy policy", style: theme.textTheme.titleMedium))])), SizedBox(height: 24.v), Divider(), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLayer2, height: 19.adaptSize, width: 19.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 18.h), child: Text("Terms & conditions", style: theme.textTheme.titleMedium))])), SizedBox(height: 4.v)])); } 
/// Section Widget
Widget _buildNinetyThree(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 20.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 3.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgVectorBlueGray9000221x18, height: 21.v, width: 18.h, margin: EdgeInsets.symmetric(vertical: 1.v)), Padding(padding: EdgeInsets.only(left: 18.h), child: Text("Close account", style: theme.textTheme.titleMedium))])), SizedBox(height: 24.v), Divider(), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLayer2, height: 19.adaptSize, width: 19.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 18.h), child: Text("Log out", style: theme.textTheme.titleMedium))])), SizedBox(height: 4.v)])); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
