import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_eleven.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_five.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_ten.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class COtp3ThreeScreen extends StatelessWidget {const COtp3ThreeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(height: 768.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 21.v), child: Container(height: 5.v, width: 175.h, decoration: BoxDecoration(color: appTheme.blueGray10002, borderRadius: BorderRadius.circular(2.h)), child: ClipRRect(borderRadius: BorderRadius.circular(2.h), child: LinearProgressIndicator(value: 0.8, backgroundColor: appTheme.blueGray10002, valueColor: AlwaysStoppedAnimation<Color>(appTheme.teal400)))))), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 10.h), decoration: AppDecoration.fillGray50, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildArrowLeft(context), SizedBox(height: 23.v), _buildVerifyPhoneNumber(context), SizedBox(height: 98.v), CustomElevatedButton(text: "Continue", margin: EdgeInsets.symmetric(horizontal: 6.h)), SizedBox(height: 98.v)])))])))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return SizedBox(height: 154.v, width: 355.h, child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftErrorcontainer, height: 14.v, width: 16.h, alignment: Alignment.topLeft, margin: EdgeInsets.only(left: 6.h, top: 10.v), onTap: () {onTapImgArrowLeft(context);}), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 192.h, child: Text("Verify your \nphone number", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.headlineMediumBluegray900.copyWith(height: 1.29))), SizedBox(height: 1.v), Opacity(opacity: 0.6, child: Text("Please enter the code we sent to +4472323121", style: theme.textTheme.labelLarge))]))), CustomAppBar(height: 58.v, leadingWidth: 58.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgLogoMark, margin: EdgeInsets.only(left: 20.h, top: 10.v, bottom: 10.v)), centerTitle: true, title: Column(children: [AppbarSubtitleFive(text: "OTP Verification code", margin: EdgeInsets.only(right: 77.h)), SizedBox(height: 3.v), AppbarSubtitleEleven(text: "Here’s your verification code: 123456")]), actions: [AppbarSubtitleTen(text: "now", margin: EdgeInsets.fromLTRB(20.h, 12.v, 20.h, 29.v))], styleType: Style.bgFill)])); } 
/// Section Widget
Widget _buildVerifyPhoneNumber(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 6.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgVerificationCodeTeal50, height: 56.v, width: 343.h), SizedBox(height: 17.v), RichText(text: TextSpan(children: [TextSpan(text: "Didn’t get the code? ", style: CustomTextStyles.labelLargeBluegray800), TextSpan(text: "Resend it.", style: CustomTextStyles.labelLargeTeal400SemiBold)]), textAlign: TextAlign.left)])); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
