import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_three.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class DocumentsScreen extends StatelessWidget {const DocumentsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: 343.h, margin: EdgeInsets.fromLTRB(16.h, 23.v, 16.h, 5.v), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 16.v), decoration: AppDecoration.outlineGray4000c.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconFinanceBlueGray90003, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Text("Card confirmation", style: theme.textTheme.titleMedium))]), SizedBox(height: 32.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconFinanceBlueGray9000324x24, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Text("Account confirmation", style: theme.textTheme.titleMedium))]), SizedBox(height: 32.v), Padding(padding: EdgeInsets.only(right: 96.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconFinance1, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Text("Statement of fees 2022", style: theme.textTheme.titleMedium))])), SizedBox(height: 32.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgHugeIconFinance1, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Text("Statement of fees 2021", style: theme.textTheme.titleMedium))])])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 45.v, leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 14.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleThree(text: "Home address")); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
