import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class AGetStarted1TwoScreen extends StatelessWidget {const AGetStarted1TwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.blueGray800, appTheme.teal40002, appTheme.blueGray800])), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, height: 14.v, width: 16.h, alignment: Alignment.centerLeft, onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 67.v), _buildView(context), SizedBox(height: 35.v), _buildTitles(context), SizedBox(height: 29.v), _buildButton(context), SizedBox(height: 5.v)]))))); } 
/// Section Widget
Widget _buildView(BuildContext context) { return SizedBox(height: 320.v, width: 311.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(height: 128.adaptSize, width: 128.adaptSize, margin: EdgeInsets.only(top: 80.v), decoration: BoxDecoration(color: appTheme.lime300, borderRadius: BorderRadius.circular(64.h)))), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgGetVerifiedIllustration, height: 213.v, width: 311.h), SizedBox(height: 93.v), Opacity(opacity: 0.2, child: Container(height: 13.v, width: 160.h, decoration: BoxDecoration(color: theme.colorScheme.errorContainer.withOpacity(0.42), borderRadius: BorderRadius.circular(80.h))))]))])); } 
/// Section Widget
Widget _buildTitles(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: Column(children: [Text("Tell us about yourself", style: CustomTextStyles.displaySmallOnErrorContainer), Opacity(opacity: 0.8, child: Container(width: 334.h, margin: EdgeInsets.symmetric(horizontal: 4.h), child: Text("Signing up shouldn’t take longer than 10 minutes and you do it all from your phone,\n\nWe’ll store any info you give us securely and only share it with your permission. ", maxLines: 5, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeOnErrorContainerSemiBold.copyWith(height: 1.38))))])); } 
/// Section Widget
Widget _buildButton(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: Column(children: [CustomElevatedButton(text: "Continue", buttonStyle: CustomButtonStyles.fillLime, buttonTextStyle: CustomTextStyles.titleSmallGeneralSansVariableTeal90001), SizedBox(height: 16.v), CustomElevatedButton(text: "Not right now", buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.titleSmallGeneralSansVariableOnErrorContainer)])); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
