import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:fintech_app/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class BCardInYourNameErrorScreen extends StatelessWidget {BCardInYourNameErrorScreen({Key? key}) : super(key: key);

TextEditingController expirydateController = TextEditingController();

TextEditingController cvvController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgBlackBackground, height: 14.v, width: 375.h), SizedBox(height: 1.v), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, margin: EdgeInsets.only(left: 14.h), onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 21.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Card in your name", style: theme.textTheme.headlineMedium), SizedBox(height: 3.v), Text("􀵔 Processed securely by PCI DSS", style: CustomTextStyles.labelLargeTeal400SemiBold_1)])), SizedBox(height: 17.v), _buildFrame(context), SizedBox(height: 16.v), _buildFrame1(context), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 11.adaptSize, width: 11.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topLeft, child: Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(left: 4.h), child: Text("!", style: CustomTextStyles.labelSmallManropeRedA70002)))), Align(alignment: Alignment.center, child: Container(height: 11.adaptSize, width: 11.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(5.h), border: Border.all(color: appTheme.redA70002, width: 1.h))))])), Opacity(opacity: 0.9, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("Use a valid card number", style: CustomTextStyles.labelLargeRedA70002)))])), Spacer(flex: 27), CustomElevatedButton(text: "Continue", margin: EdgeInsets.symmetric(horizontal: 16.h), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleMediumGeneralSansVariableBluegray20001, alignment: Alignment.center), Spacer(flex: 72)])))); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.fromLTRB(14.h, 7.v, 14.h, 6.v), decoration: AppDecoration.outlineDeepOrangeA, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text("Card number", style: CustomTextStyles.labelLargeDeeporangeA400), SizedBox(height: 5.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("1111 1111 1111 1111", style: CustomTextStyles.labelLargeGray90004), Container(height: 14.v, width: 13.h, margin: EdgeInsets.only(bottom: 2.v), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 4.h), child: Text("!", style: CustomTextStyles.labelSmallManropeDeeporangeA400))), Align(alignment: Alignment.bottomCenter, child: Container(height: 13.adaptSize, width: 13.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.deepOrangeA400, width: 1.h))))]))]), SizedBox(height: 1.v)]))); } 
/// Section Widget
Widget _buildFrame1(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomTextFormField(width: 168.h, controller: expirydateController, hintText: "Expiry date", hintStyle: CustomTextStyles.labelLargePrimary), Padding(padding: EdgeInsets.only(left: 7.h), child: CustomTextFormField(width: 168.h, controller: cvvController, hintText: "CVV", hintStyle: CustomTextStyles.labelLargePrimary, textInputAction: TextInputAction.done, suffix: Padding(padding: EdgeInsets.fromLTRB(30.h, 18.v, 19.h, 20.v), child: Text("?", style: TextStyle(color: Color(0XFF000000), fontSize: 13.076923370361328.fSize, fontFamily: 'Euclid Circular A', fontWeight: FontWeight.w400))), suffixConstraints: BoxConstraints(maxHeight: 56.v)))]))); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
