import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/custom_drop_down.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:fintech_app/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class APhoneNumber1TwoScreen extends StatelessWidget {APhoneNumber1TwoScreen({Key? key}) : super(key: key);

List<String> dropdownItemList = ["Item One", "Item Two", "Item Three"];

TextEditingController mobileNumberController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 86.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, onTap: () {onTapImgArrowLeft(context);}), Padding(padding: EdgeInsets.only(left: 70.h, top: 6.v, bottom: 3.v), child: Container(height: 5.v, width: 175.h, decoration: BoxDecoration(color: appTheme.blueGray10002, borderRadius: BorderRadius.circular(2.h)), child: ClipRRect(borderRadius: BorderRadius.circular(2.h), child: LinearProgressIndicator(value: 0.6, backgroundColor: appTheme.blueGray10002, valueColor: AlwaysStoppedAnimation<Color>(appTheme.teal400)))))])), SizedBox(height: 28.v), _buildTextContainer(context), SizedBox(height: 11.v), _buildMobileNumberInput(context), Spacer(flex: 39), CustomElevatedButton(text: "Continue", margin: EdgeInsets.only(left: 2.h), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleMediumGeneralSansVariableBluegray20001), Spacer(flex: 60)]))))); } 
/// Section Widget
Widget _buildTextContainer(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h, right: 41.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 286.h, margin: EdgeInsets.only(right: 16.h), child: Text("What phone number would you like to use?", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.headlineMediumBluegray900.copyWith(height: 1.29))), SizedBox(height: 2.v), Opacity(opacity: 0.6, child: Text("We will send you a verification code to this number.", style: theme.textTheme.labelLarge))])); } 
/// Section Widget
Widget _buildMobileNumberInput(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), decoration: AppDecoration.outlineGray30005, child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [Container(margin: EdgeInsets.only(top: 1.v), padding: EdgeInsets.symmetric(horizontal: 9.h), decoration: AppDecoration.outlineGray20001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 6.v), Opacity(opacity: 0.5, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("Country", style: CustomTextStyles.labelLargeBlack900SemiBold12))), Container(width: 75.h, margin: EdgeInsets.only(right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.img, height: 25.v, width: 20.h, margin: EdgeInsets.only(bottom: 6.v)), Padding(padding: EdgeInsets.only(top: 2.v), child: CustomDropDown(width: 50.h, icon: Container(margin: EdgeInsets.only(left: 14.h), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlack900, height: 29.v, width: 10.h)), hintText: "+44", items: dropdownItemList, contentPadding: EdgeInsets.symmetric(vertical: 1.v), onChanged: (value) {}))]))])), Padding(padding: EdgeInsets.only(top: 1.v), child: CustomTextFormField(width: 239.h, controller: mobileNumberController, hintText: "Mobile number", hintStyle: CustomTextStyles.labelLargeTeal400SemiBold12, textInputAction: TextInputAction.done, textInputType: TextInputType.phone))])); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
