import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class CAddARecipientScreen extends StatelessWidget {CAddARecipientScreen({Key? key}) : super(key: key);

TextEditingController vectorController = TextEditingController();

TextEditingController vectorController1 = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 14.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 16.v, width: 18.h, alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 8.h), onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("Add a recipient", style: theme.textTheme.headlineMedium))), SizedBox(height: 17.v), _buildAK(context), SizedBox(height: 6.v), Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: CustomTextFormField(controller: vectorController, hintText: "Someone else", hintStyle: CustomTextStyles.bodyLargeBlack900, prefix: Container(margin: EdgeInsets.fromLTRB(22.h, 26.v, 20.h, 29.v), child: CustomImageView(imagePath: ImageConstant.img24x24, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 80.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 30.v, 16.h, 30.v), child: CustomImageView(imagePath: ImageConstant.imgFrame7928, height: 15.v, width: 9.h)), suffixConstraints: BoxConstraints(maxHeight: 80.v), contentPadding: EdgeInsets.symmetric(vertical: 30.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayF)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: CustomTextFormField(controller: vectorController1, hintText: "A business / organisation", hintStyle: CustomTextStyles.bodyLargeBlack900, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(23.h, 28.v, 21.h, 30.v), child: CustomImageView(imagePath: ImageConstant.img21x21, height: 21.adaptSize, width: 21.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 80.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 30.v, 16.h, 30.v), child: CustomImageView(imagePath: ImageConstant.imgFrame7928, height: 15.v, width: 9.h)), suffixConstraints: BoxConstraints(maxHeight: 80.v), contentPadding: EdgeInsets.symmetric(vertical: 30.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayF)), SizedBox(height: 23.v), Opacity(opacity: 0.1, child: Divider(color: appTheme.black900.withOpacity(0.39))), SizedBox(height: 16.v), _buildInviteYourFriends(context), SizedBox(height: 16.v), Opacity(opacity: 0.1, child: Divider(color: appTheme.black900.withOpacity(0.39))), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildAK(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 8.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 21.v), decoration: AppDecoration.outlineGray4003f02.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Container(width: 36.adaptSize, margin: EdgeInsets.only(bottom: 2.v), padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 7.v), decoration: AppDecoration.fillTeal50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Text("AK", style: CustomTextStyles.titleMediumSFProTextPrimary)), Padding(padding: EdgeInsets.only(left: 14.h, top: 9.v, bottom: 8.v), child: Text("Myself", style: CustomTextStyles.bodyLargeBlack900)), Spacer(), CustomImageView(imagePath: ImageConstant.imgFrame7928, height: 15.v, width: 9.h, margin: EdgeInsets.only(top: 10.v, bottom: 12.v))])); } 
/// Section Widget
Widget _buildInviteYourFriends(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 16.v), decoration: AppDecoration.fillTeal50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgPlaneLight1, height: 47.v, width: 57.h), Padding(padding: EdgeInsets.only(left: 10.h, top: 3.v, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Send to friends on SmartBank", style: CustomTextStyles.titleSmallPrimary_1), SizedBox(height: 8.v), Text("Find friends", style: CustomTextStyles.labelLargeSFProTextTeal400_1.copyWith(decoration: TextDecoration.underline))])), Spacer(), CustomImageView(imagePath: ImageConstant.imgNavigationControlsTeal400, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(bottom: 33.v))])); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
