import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class SetYourBudgetScreen extends StatelessWidget {const SetYourBudgetScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 10.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Set your budget", style: theme.textTheme.headlineMedium)), Align(alignment: Alignment.centerLeft, child: Container(width: 331.h, margin: EdgeInsets.only(right: 12.h), child: Text("What’s the maximum you’d like to spend each week or month? Type in the amount below.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.labelLargeBluegray400SemiBold_2.copyWith(height: 1.38)))), SizedBox(height: 20.v), _buildGBPContainer(context), SizedBox(height: 11.v), _buildInputField(context), Spacer(flex: 26), CustomElevatedButton(text: "Continue", buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleMediumGeneralSansVariableBluegray20001), Spacer(flex: 73)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftErrorcontainer, margin: EdgeInsets.fromLTRB(10.h, 15.v, 349.h, 15.v), onTap: () {onTapArrowLeft(context);})); } 
/// Section Widget
Widget _buildGBPContainer(BuildContext context) { return Container(margin: EdgeInsets.only(right: 4.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 12.v), decoration: AppDecoration.outlineGray30001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.4, child: Padding(padding: EdgeInsets.only(top: 1.v), child: Text("Edit cycle", style: CustomTextStyles.labelLargeSFProTextBlack90012_1))), Text("􀉉 Monthly on 1", style: CustomTextStyles.labelLargeSFProTextTeal60012)])); } 
/// Section Widget
Widget _buildInputField(BuildContext context) { return Container(decoration: AppDecoration.outlineGrayC, child: Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 7.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [RichText(text: TextSpan(children: [TextSpan(text: "£", style: CustomTextStyles.titleLargeGeneralSansVariableGray90004), TextSpan(text: " "), TextSpan(text: "50", style: CustomTextStyles.displayMedium40)]), textAlign: TextAlign.left), SizedBox(height: 55.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.teal400, indent: 11.h, endIndent: 12.h))]), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("GBP", style: CustomTextStyles.labelLargeGray90004), Text("Balance: 0 GBP", style: CustomTextStyles.labelLargeTeal400SemiBold12)]))]))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
