import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_nine.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:fintech_app/widgets/app_bar/appbar_title_image.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:outline_gradient_button/outline_gradient_button.dart';class EVerifyIdentity5FiveScreen extends StatelessWidget {const EVerifyIdentity5FiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray90007, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 40.v), child: Column(children: [SizedBox(height: 40.v), CustomImageView(imagePath: ImageConstant.imgVector, height: 30.v, width: 51.h), SizedBox(height: 32.v), _buildCameraSnapshot(context), SizedBox(height: 12.v), Text("Back of the card", style: CustomTextStyles.titleMediumGeneralSansVariableOnErrorContainer), Spacer(), _buildButton(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 89.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(right: 93.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.symmetric(vertical: 4.v), onTap: () {onTapArrowLeft(context);}), AppbarSubtitleTwo(text: "Verify your identity", margin: EdgeInsets.only(left: 78.h))])), SizedBox(height: 16.v), AppbarSubtitleNine(text: "Is the back of your driving license in the frame and easy to read? If so, you’re all good to go!", margin: EdgeInsets.only(left: 7.h))])); } 
/// Section Widget
Widget _buildCameraSnapshot(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 4.h, right: 5.h), child: OutlineGradientButton(padding: EdgeInsets.only(left: 3.h, top: 3.v, right: 3.h, bottom: 3.v), strokeWidth: 3.h, gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [theme.colorScheme.onErrorContainer.withOpacity(1), theme.colorScheme.onErrorContainer.withOpacity(0)]), corners: Corners(topLeft: Radius.circular(16), topRight: Radius.circular(16), bottomLeft: Radius.circular(16), bottomRight: Radius.circular(16)), child: Container(decoration: AppDecoration.outline.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: CustomImageView(imagePath: ImageConstant.imgUnsplashWw8jbak7bo2, height: 240.v, width: 334.h, radius: BorderRadius.circular(16.h))))); } 
/// Section Widget
Widget _buildButton(BuildContext context) { return Column(children: [CustomElevatedButton(text: "Use this picture", buttonStyle: CustomButtonStyles.fillLime, buttonTextStyle: CustomTextStyles.titleSmallGeneralSansVariableTeal90001), SizedBox(height: 16.v), CustomElevatedButton(text: "Retake picture", buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.titleSmallGeneralSansVariableOnErrorContainer)]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
