import '../help_support_screen/widgets/faqs_item_widget.dart';import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/custom_floating_button.dart';import 'package:fintech_app/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class HelpSupportScreen extends StatelessWidget {HelpSupportScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 15.v), Expanded(child: SizedBox(width: double.maxFinite, child: Padding(padding: EdgeInsets.only(right: 2.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 29.v), _buildTextContainer(context), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 2.h), child: CustomTextFormField(controller: searchController, hintText: "Type a question here...", textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(8.h, 9.v, 6.h, 9.v), child: CustomImageView(imagePath: ImageConstant.imgSearchBlueGray300, height: 15.adaptSize, width: 15.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 36.v), contentPadding: EdgeInsets.only(top: 7.v, right: 29.h, bottom: 7.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL10, fillColor: appTheme.gray5001)), SizedBox(height: 21.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("Get help with your latest transaction", style: CustomTextStyles.labelLargeManropeBluegray400)), SizedBox(height: 7.v), _buildAutoLayoutContainer(context), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("Frequently asked questions", style: CustomTextStyles.labelLargeManropeBluegray400)), SizedBox(height: 6.v), _buildFAQs(context)]))))])), floatingActionButton: _buildFloatingActionButton(context))); } 
/// Section Widget
Widget _buildTextContainer(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h, right: 28.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Help & Support", style: theme.textTheme.headlineMedium), SizedBox(height: 3.v), Opacity(opacity: 0.6, child: SizedBox(width: 314.h, child: Text("Do you have any questions? Read through our FAQs below or search for an answer to your questions.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.labelLargeBluegray400SemiBold.copyWith(height: 1.38))))])); } 
/// Section Widget
Widget _buildAutoLayoutContainer(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 9.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgAvatarsLightBlueA70001, height: 34.adaptSize, width: 34.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Transfer from Leah", style: CustomTextStyles.labelLargeSFProTextBlack900_1), SizedBox(height: 4.v), Opacity(opacity: 0.5, child: Text("Thanks for dinner, 11:57 AM", style: theme.textTheme.bodySmall))])), Spacer(), Padding(padding: EdgeInsets.only(top: 11.v, bottom: 10.v), child: Text("+ 50", style: CustomTextStyles.labelLargeSFProTextGreen500))])); } 
/// Section Widget
Widget _buildFAQs(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 2.h), child: ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 8.v);}, itemCount: 5, itemBuilder: (context, index) {return FaqsItemWidget();}))); } 
/// Section Widget
Widget _buildFloatingActionButton(BuildContext context) { return CustomFloatingButton(height: 48, width: 48, child: CustomImageView(imagePath: ImageConstant.imgSupportChat, height: 24.0.v, width: 24.0.h)); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
