import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class BDebitOrCreditCardScreen extends StatelessWidget {const BDebitOrCreditCardScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.all(14.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, alignment: Alignment.centerLeft, onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 90.h), child: Column(children: [Text("Debit or credit card", style: theme.textTheme.headlineMedium), SizedBox(height: 7.v), Opacity(opacity: 0.6, child: Text("Your money is protected by licensed banks", style: theme.textTheme.labelLarge))]))), SizedBox(height: 17.v), _buildInputField(context), SizedBox(height: 15.v), _buildPassportContainer(context), SizedBox(height: 34.v), CustomElevatedButton(text: "Continue"), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildInputField(BuildContext context) { return SizedBox(height: 98.v, width: 343.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 96.v, width: 343.h, decoration: BoxDecoration())), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 7.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [RichText(text: TextSpan(children: [TextSpan(text: "£", style: CustomTextStyles.titleLargeGeneralSansVariableGray90004), TextSpan(text: " "), TextSpan(text: "50", style: CustomTextStyles.displayMedium40)]), textAlign: TextAlign.left), SizedBox(height: 55.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.teal400, indent: 11.h, endIndent: 12.h))]), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("GBP", style: CustomTextStyles.labelLargeGray90004), Text("Balance: 0 GBP", style: CustomTextStyles.labelLargeTeal400SemiBold12)]))])))])); } 
/// Section Widget
Widget _buildPassportContainer(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 15.v), decoration: AppDecoration.outlineGray4000c.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.img3dIconsOnerrorcontainer, height: 46.v, width: 40.h, margin: EdgeInsets.only(top: 1.v)), Padding(padding: EdgeInsets.only(left: 10.h, top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Debit or credit card", style: CustomTextStyles.titleMediumGeneralSansVariablePrimaryContainer), SizedBox(height: 6.v), Opacity(opacity: 0.6, child: Text("Card details added securely", style: CustomTextStyles.labelLargeGray90008_2))])), Spacer(), CustomElevatedButton(height: 32.v, width: 69.h, text: "Change", margin: EdgeInsets.only(top: 8.v, right: 3.h, bottom: 8.v), buttonStyle: CustomButtonStyles.fillTeal, buttonTextStyle: CustomTextStyles.labelMediumManropeErrorContainer11)])); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
