// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw_VSUSYuWhQmFXrPe5yLuNBMK8alYyuA',
    appId: '1:814487374485:web:d32ff0571d27c15350a99c',
    messagingSenderId: '814487374485',
    projectId: 'fintechapp-b5552',
    authDomain: 'fintechapp-b5552.firebaseapp.com',
    storageBucket: 'fintechapp-b5552.appspot.com',
    measurementId: 'G-FLB32QT7FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvsanI5mwrIfnmN2dMWBxXWLbLWXNCVxs',
    appId: '1:814487374485:android:a54ede1a3d3e55f750a99c',
    messagingSenderId: '814487374485',
    projectId: 'fintechapp-b5552',
    storageBucket: 'fintechapp-b5552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDeI90Qx64UWlLvbXYUjyX5siLsUIP3GE',
    appId: '1:814487374485:ios:fbbad2abe33bae4850a99c',
    messagingSenderId: '814487374485',
    projectId: 'fintechapp-b5552',
    storageBucket: 'fintechapp-b5552.appspot.com',
    iosBundleId: 'com.fintechapp.app',
  );
}