import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class SupportScreen extends StatelessWidget {const SupportScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildArrowLeft(context), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Talk to our team", style: theme.textTheme.headlineMedium), SizedBox(height: 59.v), Align(alignment: Alignment.center, child: SizedBox(height: 105.v, width: 135.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(height: 77.adaptSize, width: 77.adaptSize, margin: EdgeInsets.only(top: 5.v), decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer.withOpacity(1), borderRadius: BorderRadius.circular(38.h)))), CustomImageView(imagePath: ImageConstant.imgGroup212, height: 105.v, width: 135.h, alignment: Alignment.center)]))), SizedBox(height: 36.v), Align(alignment: Alignment.centerRight, child: Container(height: 18.v, width: 154.h, margin: EdgeInsets.only(right: 85.h), child: Stack(alignment: Alignment.centerLeft, children: [Opacity(opacity: 0.1, child: Align(alignment: Alignment.center, child: Container(height: 18.v, width: 154.h, decoration: BoxDecoration(color: appTheme.teal90002.withOpacity(0.39), borderRadius: BorderRadius.circular(77.h))))), Opacity(opacity: 0.1, child: Align(alignment: Alignment.centerLeft, child: Container(height: 18.v, width: 65.h, margin: EdgeInsets.only(left: 3.h), decoration: BoxDecoration(color: appTheme.teal90002.withOpacity(0.39), borderRadius: BorderRadius.circular(32.h)))))]))), SizedBox(height: 8.v), Opacity(opacity: 0.6, child: Text("Recommended", style: CustomTextStyles.labelLargeManropeGray90008)), SizedBox(height: 7.v), _buildFrame(context), SizedBox(height: 17.v), Opacity(opacity: 0.6, child: Text("Other options", style: CustomTextStyles.labelLargeManropeGray90008)), SizedBox(height: 6.v), _buildFrame1(context), SizedBox(height: 8.v), _buildFrame2(context), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 15.v), decoration: AppDecoration.fillGray100041, child: CustomAppBar(height: 14.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftErrorcontainer, margin: EdgeInsets.only(left: 10.h, right: 349.h), onTap: () {onTapArrowLeft(context);}))); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 16.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgDocChart2, height: 48.v, width: 33.h), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Chat with us", style: theme.textTheme.titleMedium), SizedBox(height: 7.v), RichText(text: TextSpan(children: [TextSpan(text: "We’ll reply in ", style: CustomTextStyles.labelLargeInterBluegray9000212), TextSpan(text: "2-5 mins", style: CustomTextStyles.labelLargeInterBluegray90002Bold)]), textAlign: TextAlign.left)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgFrame34402, height: 48.v, width: 29.h)])); } 
/// Section Widget
Widget _buildFrame1(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 16.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgDocChart2, height: 48.v, width: 33.h), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Email us", style: theme.textTheme.titleMedium), SizedBox(height: 7.v), RichText(text: TextSpan(children: [TextSpan(text: "We’ll reply in ", style: CustomTextStyles.labelLargeInterBluegray9000212), TextSpan(text: "1 working day", style: CustomTextStyles.labelLargeInterBluegray90002Bold)]), textAlign: TextAlign.left)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgFrame34402, height: 48.v, width: 29.h)])); } 
/// Section Widget
Widget _buildFrame2(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 16.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgDocChart2, height: 48.v, width: 33.h), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Call us", style: theme.textTheme.titleMedium), SizedBox(height: 5.v), RichText(text: TextSpan(children: [TextSpan(text: "Available ", style: CustomTextStyles.labelLargeInterBluegray9000212), TextSpan(text: "Mon-Fri", style: CustomTextStyles.labelLargeInterBluegray90002Bold)]), textAlign: TextAlign.left)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgFrame34402, height: 48.v, width: 29.h)])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
