import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class CallUsScreen extends StatelessWidget {const CallUsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildArrowLeft(context), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Talk to our team", style: theme.textTheme.headlineMedium), SizedBox(height: 20.v), Opacity(opacity: 0.6, child: Text("Personal accounts", style: CustomTextStyles.labelLargeManropeGray90008)), SizedBox(height: 7.v), _buildFrame(context, userName: "+44 123 4342 123", timeZone: "Mon - Fri 08:00 - 16:00 GMT"), SizedBox(height: 24.v), Opacity(opacity: 0.6, child: Text("Business accounts", style: CustomTextStyles.labelLargeManropeGray90008)), SizedBox(height: 7.v), _buildFrame(context, userName: "+44 123 4342 321", timeZone: "Mon - Fri 08:00 - 16:00 GMT"), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 15.v), decoration: AppDecoration.fillGray100041, child: CustomAppBar(height: 14.v, leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftErrorcontainer, margin: EdgeInsets.only(left: 10.h, right: 349.h), onTap: () {onTapArrowLeft(context);}))); } 
/// Common widget
Widget _buildFrame(BuildContext context, {required String userName, required String timeZone, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 16.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgGroup162703, height: 38.adaptSize, width: 38.adaptSize, margin: EdgeInsets.only(bottom: 10.v)), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(userName, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.blueGray90002)), SizedBox(height: 5.v), Opacity(opacity: 0.5, child: Text(timeZone, style: CustomTextStyles.labelLargeInterBluegray90002.copyWith(color: appTheme.blueGray90002.withOpacity(0.53))))])), Spacer(), CustomImageView(imagePath: ImageConstant.imgFrame34402, height: 38.v, width: 32.h, margin: EdgeInsets.only(bottom: 10.v))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
