import '../b_account_details_screen/widgets/button_item_widget.dart';import '../b_account_details_screen/widgets/receiver1_item_widget.dart';import 'package:fintech_app/core/app_export.dart';import 'package:flutter/material.dart';class BAccountDetailsScreen extends StatelessWidget {const BAccountDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, alignment: Alignment.centerLeft, onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 15.v), _buildAmount(context), SizedBox(height: 19.v), _buildButton(context), SizedBox(height: 16.v), _buildBankDetails(context), SizedBox(height: 16.v), _buildInformationalText(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildAmount(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h, right: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 6.v, bottom: 4.v), child: Text("500 GBP", style: theme.textTheme.headlineMedium)), CustomImageView(imagePath: ImageConstant.imgGroup162703, height: 49.adaptSize, width: 49.adaptSize)])); } 
/// Section Widget
Widget _buildButton(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Wrap(runSpacing: 8.v, spacing: 8.h, children: List<Widget>.generate(2, (index) => ButtonItemWidget())))); } 
/// Section Widget
Widget _buildBankDetails(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 2.h), decoration: AppDecoration.outlineLightBlueF, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("International transfers only", style: CustomTextStyles.labelLargeSFProTextGray90008)), Text("Share details", style: CustomTextStyles.labelLargeSFProTextTeal400)]), SizedBox(height: 7.v), ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: 4, itemBuilder: (context, index) {return Receiver1ItemWidget();})])); } 
/// Section Widget
Widget _buildInformationalText(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 2.h), decoration: AppDecoration.outlineIndigoF, child: Container(width: 343.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 6.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgInternationalPayments, height: 16.v, width: 20.h, margin: EdgeInsets.only(top: 8.v, bottom: 11.v)), Expanded(child: Container(width: 272.h, margin: EdgeInsets.only(left: 12.h), child: Text("Your bank may charge you additional fees for international payments.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray90008.copyWith(height: 1.38))))])), SizedBox(height: 23.v), Padding(padding: EdgeInsets.only(right: 36.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgTransferIcon, height: 19.v, width: 20.h, margin: EdgeInsets.only(top: 7.v, bottom: 10.v)), Expanded(child: Container(width: 242.h, margin: EdgeInsets.only(left: 12.h), child: Text("Transferred money should arrive at your SmartBank account in 1-3 days.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray90008.copyWith(height: 1.38))))])), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(right: 78.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSwift, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 12.h, top: 3.v), child: Text("Only SWIFT transfers are allowed ", style: CustomTextStyles.bodyMediumGray90008))]))]))); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
