import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_four.dart';import 'package:fintech_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:fintech_app/widgets/custom_icon_button.dart';import 'package:fintech_app/widgets/custom_switch.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class CSingleTransactionScreen extends StatelessWidget {CSingleTransactionScreen({Key? key}) : super(key: key);

bool isSelectedSwitch = false;

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildArrowLeft(context), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 6.v), child: Column(children: [_buildTransferFrom(context), SizedBox(height: 20.v), _buildTransactionStatus(context), SizedBox(height: 9.v), _buildFrame(context), SizedBox(height: 9.v), _buildFrame1(context), SizedBox(height: 13.v), _buildFrame2(context), SizedBox(height: 16.v), _buildFrame3(context), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.fillGray100041, child: Column(children: [SizedBox(height: 8.v), CustomAppBar(height: 22.v, leadingWidth: 26.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftErrorcontainer, margin: EdgeInsets.only(left: 10.h, top: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleFour(text: "From Leah"), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgAmount22x22, margin: EdgeInsets.symmetric(horizontal: 23.h))])])); } 
/// Section Widget
Widget _buildTransferFrom(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("+£50", style: theme.textTheme.titleLarge), Opacity(opacity: 0.6, child: Text("Transfer from Leah", style: CustomTextStyles.labelLargeSFProTextBlack900_2))]), Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(top: 7.v), child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgImage, height: 40.adaptSize, width: 40.adaptSize, radius: BorderRadius.circular(20.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgGroup34398LightBlueA70001, height: 9.adaptSize, width: 9.adaptSize, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 2.h))]))]); } 
/// Section Widget
Widget _buildTransactionStatus(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 9.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(top: 10.v, bottom: 9.v), child: Text("Status", style: CustomTextStyles.labelLargeManropeGray90008))), CustomElevatedButton(height: 38.v, width: 93.h, text: "Completed", buttonStyle: CustomButtonStyles.fillGreenAD, buttonTextStyle: CustomTextStyles.labelLargeManropeErrorContainer)]), SizedBox(height: 17.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.6, child: Text("Statement", style: CustomTextStyles.labelLargeManropeGray90008)), RichText(text: TextSpan(children: [TextSpan(text: "?", style: CustomTextStyles.labelLargeSFProLightblueA70001), TextSpan(text: "? Download", style: CustomTextStyles.labelLargeManropeLightblueA70001)]), textAlign: TextAlign.left)]), SizedBox(height: 30.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(top: 3.v), child: Text("Card", style: CustomTextStyles.labelLargeManropeGray90008))), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("􀍰 4405", style: CustomTextStyles.labelLargeManropeGray90008SemiBold))]), SizedBox(height: 9.v)])); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 13.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.6, child: Text("Note", style: CustomTextStyles.labelLargeGray90008SemiBold)), Text("Add", style: CustomTextStyles.labelLargeLightblueA70001)])); } 
/// Section Widget
Widget _buildFrame1(BuildContext context) { return Container(padding: EdgeInsets.all(8.h), decoration: AppDecoration.outlineLightBlueA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [Padding(padding: EdgeInsets.symmetric(vertical: 3.v), child: CustomIconButton(height: 34.adaptSize, width: 34.adaptSize, padding: EdgeInsets.all(7.h), decoration: IconButtonStyleHelper.fillGrayTL17, child: CustomImageView(imagePath: ImageConstant.imgGroup162761))), Padding(padding: EdgeInsets.only(left: 10.h, top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Add receipt", style: CustomTextStyles.labelLargeManropeLightblueA70001Bold.copyWith(decoration: TextDecoration.underline)), SizedBox(height: 3.v), Opacity(opacity: 0.5, child: Text("PDF, JPEG, or PNG less than 10MB", style: CustomTextStyles.labelLargeManropeBlack900))]))])); } 
/// Section Widget
Widget _buildFrame2(BuildContext context) { return Container(padding: EdgeInsets.all(12.h), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.6, child: Text("Money received", style: CustomTextStyles.labelLargeGray90008SemiBold)), Text("£50,00", style: CustomTextStyles.labelLargeManropeGray90008SemiBold)]), SizedBox(height: 29.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.6, child: Text("Our fee", style: CustomTextStyles.labelLargeGray90008SemiBold)), Text("£0,50", style: CustomTextStyles.labelLargeManropeGray90008SemiBold)])])); } 
/// Section Widget
Widget _buildFrame3(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 11.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(top: 8.v, bottom: 4.v), child: Text("Hide from Insights", style: CustomTextStyles.labelLargeManropeGray90008))), CustomSwitch(value: isSelectedSwitch, onChange: (value) {isSelectedSwitch = value;})])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
