import '../account_details_screen/widgets/receiver_item_widget.dart';import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_eight.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_one.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class AccountDetailsScreen extends StatelessWidget {const AccountDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 41.v), child: Column(children: [_buildBankDetails(context), SizedBox(height: 16.v), _buildInformationalText(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 88.v, leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 14.h, top: 3.v, bottom: 59.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: Column(children: [AppbarSubtitleOne(text: "GBP Account", margin: EdgeInsets.only(left: 75.h, right: 82.h)), SizedBox(height: 18.v), AppbarSubtitleEight(text: "Use your bank details to send money to your SmartBank account.")])); } 
/// Section Widget
Widget _buildBankDetails(BuildContext context) { return Container(decoration: AppDecoration.outlineLightBlueF, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("International transfers only", style: CustomTextStyles.labelLargeSFProTextGray90008)), Text("Share details", style: CustomTextStyles.labelLargeSFProTextTeal400)]), SizedBox(height: 7.v), ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: 4, itemBuilder: (context, index) {return ReceiverItemWidget();})])); } 
/// Section Widget
Widget _buildInformationalText(BuildContext context) { return Container(decoration: AppDecoration.outlineIndigoF, child: Container(width: 343.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 6.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgInternationalPayments, height: 16.v, width: 20.h, margin: EdgeInsets.only(top: 8.v, bottom: 11.v)), Expanded(child: Container(width: 272.h, margin: EdgeInsets.only(left: 12.h), child: Text("Your bank may charge you additional fees for international payments.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray90008.copyWith(height: 1.38))))])), SizedBox(height: 23.v), Padding(padding: EdgeInsets.only(right: 36.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgTransferIcon, height: 19.v, width: 20.h, margin: EdgeInsets.only(top: 7.v, bottom: 10.v)), Expanded(child: Container(width: 242.h, margin: EdgeInsets.only(left: 12.h), child: Text("Transferred money should arrive at your SmartBank account in 1-3 days.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray90008.copyWith(height: 1.38))))])), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(right: 78.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgSwift, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 12.h, top: 3.v), child: Text("Only SWIFT transfers are allowed ", style: CustomTextStyles.bodyMediumGray90008))]))]))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
