import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:fintech_app/widgets/custom_floating_text_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class PersonalDetailsScreen extends StatelessWidget {PersonalDetailsScreen({Key? key}) : super(key: key);

TextEditingController emailController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 9.v), child: Column(children: [_buildProfileNameAvatar(context), SizedBox(height: 22.v), _buildFrame(context), SizedBox(height: 16.v), _buildFrame(context), SizedBox(height: 16.v), _buildFrame3(context), SizedBox(height: 11.v), _buildFrame(context), SizedBox(height: 16.v), _buildFrame(context), SizedBox(height: 16.v), _buildFrame(context), SizedBox(height: 11.v), CustomFloatingTextField(controller: emailController, labelText: "Email", labelStyle: CustomTextStyles.labelLargeSFProTextBlack900SemiBold_1, hintText: "Email", textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress, borderDecoration: FloatingTextFormFieldStyleHelper.outlineRed, fillColor: appTheme.deepOrange50), SizedBox(height: 9.v), Align(alignment: Alignment.centerLeft, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 11.adaptSize, width: 11.adaptSize, margin: EdgeInsets.only(top: 1.v, bottom: 4.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topLeft, child: Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(left: 4.h), child: Text("!", style: CustomTextStyles.labelSmallManropeRedA70002)))), Align(alignment: Alignment.center, child: Container(height: 11.adaptSize, width: 11.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(5.h), border: Border.all(color: appTheme.redA70002, width: 1.h))))])), Opacity(opacity: 0.9, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("Verify this email", style: CustomTextStyles.labelLargeRedA70002)))])), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(14.h, 15.v, 345.h, 15.v), onTap: () {onTapArrowLeft(context);})); } 
/// Section Widget
Widget _buildProfileNameAvatar(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("My Profile", style: theme.textTheme.headlineMedium), Text("Personal details", style: CustomTextStyles.titleMediumBluegray400)])), SizedBox(height: 60.v, width: 56.h, child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.all(12.h), decoration: AppDecoration.fillTeal5003.copyWith(borderRadius: BorderRadiusStyle.circleBorder28), child: Text("AK", style: theme.textTheme.titleLarge))), CustomImageView(imagePath: ImageConstant.imgFrame162701, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 3.h))]))]); } 
/// Section Widget
Widget _buildFrame3(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 14.h), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 7.v), Opacity(opacity: 0.5, child: Text("Date of birth", style: CustomTextStyles.labelLargeBlack900SemiBold12)), SizedBox(height: 5.v), Opacity(opacity: 0.5, child: Text("01/01/1994", style: CustomTextStyles.bodyMediumBlack900)), SizedBox(height: 10.v), Divider(color: appTheme.teal600)])); } 
/// Common widget
Widget _buildFrame(BuildContext context) { return Container(width: 343.h, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 9.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.5, child: Text("Legal last name", style: CustomTextStyles.labelLargeBlack900SemiBold12)), SizedBox(height: 3.v), Opacity(opacity: 0.5, child: Text("UXUI", style: CustomTextStyles.labelLargeSFProTextBlack900))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
