import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_nine.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class ALiveCameraPreviewScreen extends StatelessWidget {const ALiveCameraPreviewScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: appTheme.gray90005, appBar: _buildAppBar(context), body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(color: appTheme.gray90005, image: DecorationImage(image: AssetImage(ImageConstant.img167aLiveCamera), fit: BoxFit.cover)), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 39.h, vertical: 27.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgSelfiePreview, height: 477.v, width: 296.h, radius: BorderRadius.circular(148.h)), SizedBox(height: 60.v), Padding(padding: EdgeInsets.only(left: 111.h, right: 106.h), child: Column(children: [Container(padding: EdgeInsets.all(3.h), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder40), child: Container(height: 72.adaptSize, width: 72.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.onErrorContainer.withOpacity(1), borderRadius: BorderRadius.circular(36.h), border: Border.all(color: appTheme.blueGray900, width: 2.h)))), SizedBox(height: 10.v), CustomImageView(imagePath: ImageConstant.imgOnfidoLogo, height: 15.v, width: 63.h)]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 70.v, leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.only(left: 16.h, top: 4.v, bottom: 39.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: Column(children: [AppbarSubtitleTwo(text: "Verify your identity", margin: EdgeInsets.only(left: 26.h, right: 33.h)), SizedBox(height: 17.v), AppbarSubtitleNine(text: "Position your face in the oval below")])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
