import '../messages_screen/widgets/frame1_item_widget.dart';import '../messages_screen/widgets/frame2_item_widget.dart';import 'package:fintech_app/core/app_export.dart';import 'package:flutter/material.dart';class MessagesScreen extends StatelessWidget {const MessagesScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("Messages", style: theme.textTheme.headlineMedium)), SizedBox(height: 12.v), Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("Today", style: CustomTextStyles.labelLargeSFProDisplayGray60001))), SizedBox(height: 8.v), _buildFrame(context), SizedBox(height: 18.v), Opacity(opacity: 0.6, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("This Week", style: CustomTextStyles.labelLargeSFProDisplayGray60001))), SizedBox(height: 9.v), _buildFrame1(context)])))); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 2.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 10.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 23.v);}, itemCount: 2, itemBuilder: (context, index) {return Frame1ItemWidget();})); } 
/// Section Widget
Widget _buildFrame1(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 2.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 11.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 23.v);}, itemCount: 5, itemBuilder: (context, index) {return Frame2ItemWidget();})); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
