import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_three.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:fintech_app/widgets/custom_search_view.dart';import 'package:fintech_app/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class SelectLanguageScreen extends StatelessWidget {SelectLanguageScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

TextEditingController languageSelectController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 2.v), child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(children: [CustomSearchView(controller: searchController, hintText: "Search"), SizedBox(height: 16.v), Container(padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 16.v), decoration: AppDecoration.outlineGray6000f.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomTextFormField(controller: languageSelectController, hintText: "English (US)", hintStyle: CustomTextStyles.titleMediumSFProDisplayGray90001, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.all(16.h), child: CustomImageView(imagePath: ImageConstant.imgUsUnitedStates, height: 15.v, width: 20.h)), prefixConstraints: BoxConstraints(maxHeight: 48.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgCheck, height: 11.adaptSize, width: 11.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.symmetric(vertical: 14.v), borderDecoration: TextFormFieldStyleHelper.fillGrayTL12, fillColor: appTheme.gray10004.withOpacity(0.5)), SizedBox(height: 26.v), _buildLanguageSelect(context), SizedBox(height: 38.v), _buildLanguageSelect1(context), SizedBox(height: 39.v), _buildLanguageSelect2(context), SizedBox(height: 39.v), _buildLanguageSelect3(context), SizedBox(height: 39.v), _buildLanguageSelect4(context), SizedBox(height: 39.v), _buildLanguageSelect5(context), SizedBox(height: 38.v), _buildLanguageSelect6(context), SizedBox(height: 39.v), _buildLanguageSelect7(context), SizedBox(height: 39.v), _buildLanguageSelect8(context), SizedBox(height: 39.v), _buildLanguageSelect9(context), SizedBox(height: 39.v)]))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 49.v, leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 14.h, top: 15.v, bottom: 20.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleThree(text: "Select language")); } 
/// Section Widget
Widget _buildLanguageSelect(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgGbUkmUnited, height: 15.v, width: 20.h, margin: EdgeInsets.only(top: 2.v, bottom: 4.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("English (UK)", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 
/// Section Widget
Widget _buildLanguageSelect1(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgIdIndonesia, height: 15.v, width: 20.h, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("Indonesian", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 
/// Section Widget
Widget _buildLanguageSelect2(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgRuRussianFederation, height: 15.v, width: 20.h, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("Russian", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 
/// Section Widget
Widget _buildLanguageSelect3(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgFrFrance, height: 15.v, width: 20.h, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("French", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 
/// Section Widget
Widget _buildLanguageSelect4(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgCnChina, height: 15.v, width: 20.h, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("Chinese", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 
/// Section Widget
Widget _buildLanguageSelect5(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgJpJapan, height: 15.v, width: 20.h, margin: EdgeInsets.only(top: 2.v, bottom: 4.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("Japanese", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 
/// Section Widget
Widget _buildLanguageSelect6(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgDeGermany, height: 15.v, width: 20.h, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("German", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 
/// Section Widget
Widget _buildLanguageSelect7(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgNlNetherlands, height: 15.v, width: 20.h, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("Netherland", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 
/// Section Widget
Widget _buildLanguageSelect8(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgPlPoland, height: 15.v, width: 20.h, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("Polish", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 
/// Section Widget
Widget _buildLanguageSelect9(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgUaUkraine, height: 15.v, width: 20.h, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("Ukrainian", style: CustomTextStyles.titleMediumSFProDisplayGray90001)), Spacer(), Container(height: 20.adaptSize, width: 20.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(10.h), border: Border.all(color: appTheme.blueGray200, width: 1.h)))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
