import 'package:fintech_app/core/app_export.dart';import 'package:flutter/material.dart';class ATopTheAccountScreen extends StatelessWidget {const ATopTheAccountScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.all(14.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 2.h, right: 92.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Top up the account", style: theme.textTheme.headlineMedium), SizedBox(height: 4.v), Opacity(opacity: 0.6, child: Text("Choose your preferred method", style: theme.textTheme.labelLarge))])), SizedBox(height: 22.v), _buildTopUpAccountContainer(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildTopUpAccountContainer(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Column(children: [_buildPassportContainer(context, userImage: ImageConstant.imgTopUpAccountIcons, transferMessage: "Debit or credit card"), SizedBox(height: 8.v), _buildPassportContainer(context, userImage: ImageConstant.imgTopUpAccountIconsTeal50, transferMessage: "Open banking transfer"), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Opacity(opacity: 0.9, child: Text("Or transfer manually", style: CustomTextStyles.labelLargeSFProTextGray90008SemiBold))), SizedBox(height: 11.v), _buildPassportContainer(context, userImage: ImageConstant.imgTopUpAccountIconsTeal50, transferMessage: "Get account details")])); } 
/// Common widget
Widget _buildPassportContainer(BuildContext context, {required String userImage, required String transferMessage, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 19.v), decoration: AppDecoration.outlineGray4000c.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: userImage, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 10.h, top: 11.v, bottom: 6.v), child: Text(transferMessage, style: CustomTextStyles.titleMediumGeneralSansVariablePrimaryContainer.copyWith(color: theme.colorScheme.primaryContainer.withOpacity(1)))), Spacer(), CustomImageView(imagePath: ImageConstant.imgChevron, height: 40.v, width: 41.h)])); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
