import '../privacy_screen/widgets/personalisedemails_item_widget.dart';import '../privacy_screen/widgets/privacytoggles_item_widget.dart';import 'package:fintech_app/core/app_export.dart';import 'package:flutter/material.dart';class PrivacyScreen extends StatelessWidget {const PrivacyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 15.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("Privacy", style: theme.textTheme.headlineMedium)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("Marketing", style: CustomTextStyles.labelLargeManropeBluegray400)), SizedBox(height: 6.v), _buildPrivacyToggles(context), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("Promotions", style: CustomTextStyles.labelLargeManropeBluegray400)), SizedBox(height: 7.v), _buildPrivacyToggles1(context)]))))])))); } 
/// Section Widget
Widget _buildPrivacyToggles(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.fillOnErrorContainer, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: 3, itemBuilder: (context, index) {return PersonalisedemailsItemWidget();}), SizedBox(height: 1.v), Divider(color: theme.colorScheme.onErrorContainer.withOpacity(1)), SizedBox(height: 2.v)])); } 
/// Section Widget
Widget _buildPrivacyToggles1(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.fillOnErrorContainer, child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: 3, itemBuilder: (context, index) {return PrivacytogglesItemWidget();})); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
