import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_three.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:fintech_app/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class BOwnTransferBlurScreen extends StatelessWidget {BOwnTransferBlurScreen({Key? key}) : super(key: key);

TextEditingController frameController = TextEditingController();

TextEditingController frameController1 = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildSAVINGSAccount(context), Container(padding: EdgeInsets.all(16.h), child: Column(children: [CustomTextFormField(controller: frameController, hintText: "Transfer title", hintStyle: CustomTextStyles.bodyMediumPrimary), SizedBox(height: 16.v), CustomTextFormField(controller: frameController1, hintText: "Add a note (optional)", hintStyle: CustomTextStyles.bodyMediumPrimary, textInputAction: TextInputAction.done), SizedBox(height: 15.v), _buildInputField(context), SizedBox(height: 50.v), CustomElevatedButton(text: "Continue"), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildSAVINGSAccount(BuildContext context) { return SizedBox(height: 107.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(left: 16.h, top: 29.v, right: 16.h), padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 15.v), decoration: AppDecoration.outlineTeal600.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("SAVINGS Account (300 gBP)".toUpperCase(), style: CustomTextStyles.titleSmallManropePrimaryContainer), SizedBox(height: 5.v), Opacity(opacity: 0.5, child: Text("2365423532", style: CustomTextStyles.labelLargeSFProDisplayGray9000212))])), CustomImageView(imagePath: ImageConstant.imgFrame34402, height: 46.v, width: 9.h)]))), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 3.v), child: Text("Transfer to", style: CustomTextStyles.labelLargeBlack900SemiBold_1))), CustomAppBar(height: 52.v, leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 14.h, top: 15.v, bottom: 23.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleThree(text: "Transfer"), styleType: Style.bgFill_1)])); } 
/// Section Widget
Widget _buildInputField(BuildContext context) { return SizedBox(height: 98.v, width: 343.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 96.v, width: 343.h, decoration: BoxDecoration())), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 7.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 5.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("£ 250 ", style: theme.textTheme.displayMedium), SizedBox(height: 55.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.teal400, indent: 10.h, endIndent: 13.h))]), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Transfer amount", style: CustomTextStyles.labelLargeGray90004), Text("Balance: 0 GBP", style: CustomTextStyles.labelLargeTeal400SemiBold12)]))])))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
