import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_nine.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_two.dart';import 'package:fintech_app/widgets/app_bar/appbar_title_image.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class CVerifyIdentity3FiveScreen extends StatelessWidget {const CVerifyIdentity3FiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray90007, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 40.v), child: Column(children: [SizedBox(height: 11.v), _buildMask(context), SizedBox(height: 12.v), Text("Front of the card", style: CustomTextStyles.titleMediumGeneralSansVariableOnErrorContainer), Spacer(), _buildButton(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 89.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(right: 94.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeftOnerrorcontainer, margin: EdgeInsets.symmetric(vertical: 4.v), onTap: () {onTapArrowLeft(context);}), AppbarSubtitleTwo(text: "Verify your identity", margin: EdgeInsets.only(left: 78.h))])), SizedBox(height: 16.v), AppbarSubtitleNine(text: "Is the front of your driving license in the frame and easy to read? If so, you’re all good to go!", margin: EdgeInsets.only(left: 6.h))])); } 
/// Section Widget
Widget _buildMask(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, shape: RoundedRectangleBorder(side: BorderSide(width: 3.h), borderRadius: BorderRadiusStyle.roundedBorder16), child: Container(height: 240.v, width: 334.h, decoration: AppDecoration.outline.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgUnsplashWw8jbak7bo240x334, height: 240.v, width: 334.h, radius: BorderRadius.circular(16.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgUkIdCardTemp212x332, height: 212.v, width: 332.h, radius: BorderRadius.circular(16.h), alignment: Alignment.center)]))); } 
/// Section Widget
Widget _buildButton(BuildContext context) { return Column(children: [CustomElevatedButton(text: "Use this picture", buttonStyle: CustomButtonStyles.fillLime, buttonTextStyle: CustomTextStyles.titleSmallGeneralSansVariableTeal90001), SizedBox(height: 16.v), CustomElevatedButton(text: "Retake picture", buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.titleSmallGeneralSansVariableOnErrorContainer)]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
