import '../b_transactions_screen/widgets/ak2_item_widget.dart';import '../b_transactions_screen/widgets/transactions2_item_widget.dart';import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/app_bar/appbar_leading_image.dart';import 'package:fintech_app/widgets/app_bar/appbar_subtitle_three.dart';import 'package:fintech_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:fintech_app/widgets/app_bar/custom_app_bar.dart';import 'package:fintech_app/widgets/custom_drop_down.dart';import 'package:fintech_app/widgets/custom_floating_button.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class BTransactionsScreen extends StatelessWidget {BTransactionsScreen({Key? key}) : super(key: key);

List<String> dropdownItemList = ["Item One", "Item Two", "Item Three"];

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildHeader(context), SizedBox(height: 17.v), Padding(padding: EdgeInsets.only(left: 16.h), child: CustomDropDown(width: 240.h, icon: Container(margin: EdgeInsets.fromLTRB(15.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgVectorTeal6009x15, height: 9.v, width: 15.h)), hintText: "adrian’s account - gbp".toUpperCase(), hintStyle: CustomTextStyles.titleSmallManropePrimaryContainer, alignment: Alignment.centerLeft, items: dropdownItemList, onChanged: (value) {})), SizedBox(height: 11.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: _buildFrame(context, date: "Today", price: "+ 3500")), SizedBox(height: 7.v), _buildFrame2(context), SizedBox(height: 17.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: _buildFrame(context, date: "16 APR 2022", price: "- 1775.88")), SizedBox(height: 26.v), _buildAK(context), SizedBox(height: 35.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: _buildFrame(context, date: "15 APR 2022", price: "- 265")), SizedBox(height: 8.v), _buildTransactions(context), SizedBox(height: 23.v)])), floatingActionButton: _buildFloatingActionButton(context))); } 
/// Section Widget
Widget _buildHeader(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 10.v), decoration: AppDecoration.fillGray10004, child: Column(children: [SizedBox(height: 6.v), CustomAppBar(height: 23.v, leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 14.h, top: 4.v, bottom: 4.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleThree(text: "Transactions"), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgAmount22x20, margin: EdgeInsets.only(left: 13.h, right: 13.h, bottom: 1.v))])])); } 
/// Section Widget
Widget _buildFrame2(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 16.v), decoration: AppDecoration.fillOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Container(padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 1.v), decoration: AppDecoration.fillGray6001e.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgEmoji, height: 20.v, width: 17.h), SizedBox(height: 2.v), CustomImageView(imagePath: ImageConstant.imgGroup34398, height: 8.adaptSize, width: 8.adaptSize, alignment: Alignment.centerRight)])), Padding(padding: EdgeInsets.only(left: 15.h, top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Salary payment", style: CustomTextStyles.labelLargeSFProTextBlack900_1), SizedBox(height: 4.v), Text("5 Oct 2020, 2:36 PM", style: CustomTextStyles.bodySmallGray800_1)])), Spacer(), Padding(padding: EdgeInsets.only(bottom: 22.v), child: Text("+ 3500", style: CustomTextStyles.labelLargeSFProTextGreen500))])); } 
/// Section Widget
Widget _buildAK(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 19.h), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 21.v);}, itemCount: 5, itemBuilder: (context, index) {return Ak2ItemWidget();})); } 
/// Section Widget
Widget _buildTransactions(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 17.v), decoration: AppDecoration.outlineBluegray1003f01.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 21.v);}, itemCount: 2, itemBuilder: (context, index) {return Transactions2ItemWidget();})); } 
/// Section Widget
Widget _buildFloatingActionButton(BuildContext context) { return CustomFloatingButton(height: 48, width: 48, child: CustomImageView(imagePath: ImageConstant.imgButton, height: 24.0.v, width: 24.0.h)); } 
/// Common widget
Widget _buildFrame(BuildContext context, {required String date, required String price, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(date, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.gray800.withOpacity(0.6))), Text(price, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.gray800.withOpacity(0.6)))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
