import 'package:fintech_app/core/app_export.dart';import 'package:fintech_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class AOtp1ThreeScreen extends StatelessWidget {const AOtp1ThreeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray50, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 86.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 14.v, width: 16.h, onTap: () {onTapImgArrowLeft(context);}), Padding(padding: EdgeInsets.only(left: 70.h, top: 6.v, bottom: 3.v), child: Container(height: 5.v, width: 175.h, decoration: BoxDecoration(color: appTheme.blueGray10002, borderRadius: BorderRadius.circular(2.h)), child: ClipRRect(borderRadius: BorderRadius.circular(2.h), child: LinearProgressIndicator(value: 0.8, backgroundColor: appTheme.blueGray10002, valueColor: AlwaysStoppedAnimation<Color>(appTheme.teal400)))))])), SizedBox(height: 27.v), Padding(padding: EdgeInsets.only(right: 73.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 192.h, margin: EdgeInsets.only(right: 78.h), child: Text("Verify your \nphone number", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.headlineMediumBluegray900.copyWith(height: 1.29))), SizedBox(height: 1.v), Opacity(opacity: 0.6, child: Text("Please enter the code we sent to +4472323121", style: theme.textTheme.labelLarge))])), SizedBox(height: 23.v), _buildVerifyPhoneNumber(context), Spacer(flex: 33), CustomElevatedButton(text: "Continue", buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleMediumGeneralSansVariableBluegray20001), Spacer(flex: 66)])))); } 
/// Section Widget
Widget _buildVerifyPhoneNumber(BuildContext context) { return Column(children: [CustomImageView(imagePath: ImageConstant.imgVerificationCode, height: 56.v, width: 343.h), SizedBox(height: 17.v), RichText(text: TextSpan(children: [TextSpan(text: "Didn’t get the code? ", style: CustomTextStyles.labelLargeBluegray800), TextSpan(text: "Resend it.", style: CustomTextStyles.labelLargeTeal400SemiBold)]), textAlign: TextAlign.left)]); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
